from django.utils.translation import ugettext_lazy as _

CHOICES = {
    'region': [
        ('1', _("Toshkent")),
        ('2', _("Toshkent viloyati")),
        ('3', _("Samarqand viloyati")),
        ('4', _("Buxoro viloyati")),
        ('5', _("Andijon viloyati")),
        ('6', _("Farg'ona viloyati")),
        ('7', _("Namangan viloyati")),
        ('8', _("Qashqadaryo viloyati")),
        ('9', _("Surhondaryo viloyati")),
        ('10', _("Sirdaryo viloyati")),
        ('11', _("Jizzax viloyati")),
        ('12', _("Xorazm viloyati")),
        ('13', _("Navoiy viloyati")),
        ('14', _("Qoraqalpog'iston Respublikasi")),
    ],
    'gender': [
        ('1', _("Erkak")),
        ('2', _("Ayol")),
    ],
}

REGIONS = {
    'Ташкент': "Toshkent",
    'Ташкентская область': "Toshkent viloyati",
    'Самаркандская область': "Samarqand viloyati",
    'Бухарская область': "Buxoro viloyati",
    'Андижанская область': "Andijon viloyati",
    'Ферганская область': "Farg'ona viloyati",
    'Наманганская область': "Namangan viloyati",
    'Кашкадарьинская область': "Qashqadaryo viloyati",
    'Сурхандарьинская область': "Surhondaryo viloyati",
    'Сырдарьинская область': "Sirdaryo viloyati",
    'Джизакская область': "Jizzax viloyati",
    'Хорезмская область': "Xorazm viloyati",
    'Навоийская область': "Navoiy viloyati",
    'Республика Каракалпакстан': "Qoraqalpog'iston Respublikasi",
    'Toshkent': "Ташкент",
    'Toshkent viloyati': "Ташкентская область",
    'Samarqand viloyati': "Самаркандская область",
    'Buxoro viloyati': "Бухарская область",
    'Andijon viloyati': "Андижанская область",
    'Farg\'ona viloyati': "Ферганская область",
    'Namangan viloyati': "Наманганская область",
    'Qashqadaryo viloyati': "Кашкадарьинская область",
    'Surhondaryo viloyati': "Сурхандарьинская область",
    'Sirdaryo viloyati': "Сырдарьинская область",
    'Jizzax viloyati': "Джизакская область",
    'Xorazm viloyati': "Хорезмская область",
    'Navoiy viloyati': "Навоийская область",
    'Qoraqalpog\'iston Respublikasi': "Республика Каракалпакстан",
}
