# Generated by Django 3.2 on 2021-09-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'OITS',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Allergiya',
            },
        ),
        migrations.CreateModel(
            name='Anesthesia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Narkoz',
            },
        ),
        migrations.CreateModel(
            name='Asthma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Bronzial astma',
            },
        ),
        migrations.CreateModel(
            name='Diabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Qandli diabet',
            },
        ),
        migrations.CreateModel(
            name='Dizziness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Bosh aylanishi',
            },
        ),
        migrations.CreateModel(
            name='Hepatitis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Gepatit B',
            },
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
            ],
            options={
                'verbose_name': 'Qon bosimi',
            },
        ),
    ]
