# Generated by Django 3.2 on 2021-09-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0002_auto_20210902_1242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asthma',
            options={'verbose_name': 'Bronxial astma'},
        ),
    ]
