# Generated by Django 3.2 on 2021-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('illness', '0003_alter_asthma_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Spirtli ichimlik ichasizmi?',
            },
        ),
        migrations.CreateModel(
            name='Blood_disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Qon kasali',
            },
        ),
        migrations.CreateModel(
            name='Epilepsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Epilepsiya',
            },
        ),
        migrations.CreateModel(
            name='Heart_attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Yurak xurujiga uchraganmisiz?',
            },
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Doimiy dorilar',
            },
        ),
        migrations.CreateModel(
            name='Oncologic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Onkologik kasalliklar',
            },
        ),
        migrations.CreateModel(
            name='Pregnancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Homiladorlik',
            },
        ),
        migrations.CreateModel(
            name='Stroke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Insultga uchraganmisiz?',
            },
        ),
        migrations.CreateModel(
            name='Tuberculosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(verbose_name='Qiymat')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tavsif')),
            ],
            options={
                'verbose_name': 'Sil kasalligi',
            },
        ),
    ]
