# Generated by Django 3.2 on 2021-09-19 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '__first__'),
        ('patient', '0002_other_illness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('address', models.CharField(max_length=255, verbose_name='Manzil')),
                ('orientir', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mo'ljal")),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Kenglik')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Uzunlik')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.language', verbose_name='Til')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.region', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Shifoxona',
                'verbose_name_plural': 'Shifoxonalar',
            },
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='FISh')),
                ('worktime_begin', models.TimeField(verbose_name='Ish vaqti boshlanishi')),
                ('worktime_end', models.TimeField(verbose_name='Ish vaqti tugashi')),
                ('is_fullday', models.BooleanField(verbose_name='24 soat rejimi')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Telefon raqami')),
                ('image', models.ImageField(upload_to='dentists/photos/', verbose_name='Rasmi')),
                ('speciality', models.CharField(max_length=500, verbose_name='Soha')),
                ('experience', models.IntegerField(verbose_name='Tajriba')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.clinic', verbose_name='Shifoxona')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.gender', verbose_name='Jins')),
            ],
            options={
                'verbose_name': 'Tish shifokori',
                'verbose_name_plural': 'Tish shifokorlari',
            },
        ),
        migrations.CreateModel(
            name='Cabinet_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dentists/cabinet_photos/', verbose_name='Rasm')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.dentist', verbose_name='Tish shifokori')),
            ],
            options={
                'verbose_name': 'Kabinet rasmi',
                'verbose_name_plural': 'Kabinet rasmlari',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, verbose_name='Sabab')),
                ('comment', models.TextField(verbose_name='Izohlar')),
                ('time', models.DateTimeField(verbose_name='Qabul vaqti')),
                ('attend', models.CharField(max_length=50, verbose_name='Qabul holati')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.dentist', verbose_name='Tish shifokori')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name': "So'rov",
                'verbose_name_plural': "So'rovlar",
            },
        ),
    ]
