# Generated by Django 3.2 on 2021-09-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='image',
            field=models.ImageField(default='dentists/photos/default.png', upload_to='dentists/photos/', verbose_name='Rasmi'),
        ),
    ]
