# Generated by Django 3.2 on 2021-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_alter_dentist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.DateTimeField(default=None, verbose_name='Qabul vaqti'),
        ),
    ]
