# Generated by Django 3.2 on 2021-09-02 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseapp', '__first__'),
        ('illness', '0003_alter_asthma_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25, verbose_name='Telefon raqami')),
                ('address', models.CharField(max_length=255, verbose_name='Manzili')),
                ('birthday', models.DateField(verbose_name="Tug'ilgan sanasi")),
                ('image', models.ImageField(upload_to='patients/photos/', verbose_name='Rasmi')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseapp.language', verbose_name='Tili')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bemor')),
            ],
            options={
                'verbose_name': 'Bemor',
                'verbose_name_plural': 'Bemorlar',
            },
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.aids', verbose_name='OITS')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.allergy', verbose_name='Allergiya')),
                ('anesthesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.anesthesia', verbose_name='Narkoz')),
                ('asthma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.asthma', verbose_name='Bronxial astma')),
                ('diabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.diabet', verbose_name='Qandli diabet')),
                ('dizziness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.dizziness', verbose_name='Bosh aylanishi')),
                ('hepatitis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.hepatitis', verbose_name='Gepatit B')),
                ('pressure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='illness.pressure', verbose_name='Qon bosimi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.user', verbose_name='Bemor')),
            ],
            options={
                'verbose_name_plural': 'Bemor kasalliklari',
            },
        ),
    ]
